### ISSUE TITLE
upgrade python version;

### ISSUE THREAD

**Issue by DAKExDUCK** [AITUSAIT/pocket-moodle#83]
docs - https://docs.aiogram.dev/en/latest/dispatcher/webhook.html
guide - <https://habr.com/ru/articles/730310/>

migrate to python3.11
use aiogram 3.X
requirements set to static versions without trash, only needed. Remove unused, remove not imported

**Comment by amdRyzen5600X** [comment]
> migrate to python3.11

почему на 3.11, почему не 3.12?

**Comment by DAKExDUCK** [comment]
> > migrate to python3.11
> 
> почему на 3.11, почему не 3.12?

а 12 стабильный? Все пакеты норм работают? Просто когда только выходил 11 долго еще пакеты переходили, не работали толком
